server:
  port: 8083
hm:
  db:
    name: hm-user # 数据库名，供 shared-jdbc.yaml 拼接 url
  swagger:
    title: 用户服务接口文档 # 供 shared-swagger.yaml 使用
    package: com.hmall.user.controller
  jwt:
    location: classpath:hmall.jks
    alias: hmall
    password: ${hm.jwt.pw}
    tokenTTL: 30m
